// Builds app/static/icons.svg (an SVG <symbol> sprite) from pinned lucide-static.
// Usage: node build_icons.mjs   (re-run when adding an icon name below)
import fs from 'node:fs';
const NAMES = ['mic','square','trash-2','upload','x','check','circle-check','circle-x','circle-alert','triangle-alert',
  'info','sun','moon','monitor','search','copy','download','settings','rotate-cw','chevron-down','chevron-up',
  'arrow-up','arrow-down','file-audio','ban','clock','pause','play'];
const dir = new URL('./node_modules/lucide-static/icons/', import.meta.url);
const pkg = JSON.parse(fs.readFileSync(new URL('./node_modules/lucide-static/package.json', import.meta.url)));
let out = `<svg xmlns="http://www.w3.org/2000/svg" style="display:none">\n<!-- Generated by tools/ux/build_icons.mjs from lucide-static ${pkg.version} (ISC license). Do not edit by hand. -->\n`;
for (const n of NAMES) {
  const svg = fs.readFileSync(new URL(`${n}.svg`, dir), 'utf8');
  const inner = svg.replace(/<!--.*?-->/s, '').replace(/^[\s\S]*?<svg[^>]*>/, '').replace(/<\/svg>\s*$/, '').trim()
    .split('\n').map((l) => '  ' + l.trim()).join('\n');
  out += `<symbol id="i-${n}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">\n${inner}\n</symbol>\n`;
}
// Brand mark from docs/brand-guide.html: pixel "S" plus text cursor (74x70 grid).
out += `<symbol id="mark" viewBox="0 0 74 70"><g fill="currentColor"><rect x="10" y="0" width="40" height="10"/><rect x="0" y="10" width="10" height="20"/><rect x="10" y="30" width="30" height="10"/><rect x="40" y="40" width="10" height="20"/><rect x="0" y="60" width="40" height="10"/><rect x="62" y="0" width="12" height="70"/></g></symbol>\n`;
out += '</svg>\n';
fs.writeFileSync(new URL('../../app/static/icons.svg', import.meta.url), out);
console.log('icons:', NAMES.length);
